### ISSUE TITLE
An error occured loading this property page (VS 2015)

### ISSUE THREAD

**Issue by RMDarth** [buchizo/ClaudiaIDE#39]
Extension failed to load, options showing "An error occured loading this property page".
Activity log says "Could not load file or assembly Microsoft.VisualStudio.Shell.15.0" (which is VS2017 assembly I suppose, and I only have VS2015 installed)

**Comment by buchizo** [comment]
@RMDarth 

Sorry, ver 2.0.x include critical error due to VS2017 runtime about this version running on VS2015. I tried fix this issue, but some code depend on vs 2017 runtime. Unfortunately I decide don't support VS2015 about ClaudiaIDE 2.0.x. If you still like this extension, you can use [1.28.6](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release1.28.6).

Thanks,

**Comment by RMDarth** [comment]
Ok thanks I'll stick with old version
