### ISSUE TITLE
Failed to apply custom text editor background color

### ISSUE THREAD

**Issue by AIGRIND-LLC** [buchizo/ClaudiaIDE#54]
Hello!
After the last update the extension does not display the custom color assigned to the text editor.
And the background image has got an incorrect offset.

Here is the correct layout when the extension is **disabled**.
<img src="https://user-images.githubusercontent.com/6168693/58161933-7eb61b80-7c81-11e9-8dd6-f1c1b6309900.png" width="400">

And here is the wrong layout when the extension is **enabled**.
<img src="https://user-images.githubusercontent.com/6168693/58161974-9097be80-7c81-11e9-8b4b-f40682ce5f60.png" width="400">

There is the extension settings:
<img src="https://user-images.githubusercontent.com/6168693/58162401-6692cc00-7c82-11e9-8c97-598808be6417.png" width="400">

And here is the test image just in case.
<img src="https://user-images.githubusercontent.com/6168693/58162518-a194ff80-7c82-11e9-9eae-b9726f2ebaea.png" width="250">

**Comment by AIGRIND-LLC** [comment]
And here is the test image just in case.
![test](https://user-images.githubusercontent.com/6168693/58162518-a194ff80-7c82-11e9-9eae-b9726f2ebaea.png)

**Comment by buchizo** [comment]
That is by design on ver2.2.x.

#### Details

Ver 2.1.0 is depends on editor adornment layer on text editor part. Text editor part is red dashed line as follows:

![image](https://user-images.githubusercontent.com/1254213/58229744-76d3a580-7d6d-11e9-9554-d84e03aabb3f.png)

ClaudiaIDE add image layer on editor adornment layer.

![image](https://user-images.githubusercontent.com/1254213/58230995-d2536280-7d70-11e9-81a5-7f6319e6ecf4.png)

result:

![image](https://user-images.githubusercontent.com/1254213/58231017-e008e800-7d70-11e9-917d-d347197e7739.png)
![image](https://user-images.githubusercontent.com/1254213/58231115-23635680-7d71-11e9-8771-a7f94b916bae.png)

An adornment layer is inside some parts (e.g. scrollbar, line number).
However adornment layer is visual port as virtual area. ClaudiaIDE should be reset position when scrolling. So that is occurred flickering.

Ver 2.2.x is not depends on editor adornment layer. Ver2.2.0 add background image to document of editor window. Editor window is bottom layer than other parts (e.g. scrollbar, line number, adornment layer and text editor). Ver 2.2.x ClaudiaIDE need to transparent from solid color of text background color because ClaudiaIDE's background image set to bottom than text editor.

![image](https://user-images.githubusercontent.com/1254213/58233905-3f1e2b00-7d78-11e9-93c2-5635cb7054c6.png)

result:

![image](https://user-images.githubusercontent.com/1254213/58233937-51986480-7d78-11e9-8dd2-ceeabf71ac10.png)
![image](https://user-images.githubusercontent.com/1254213/58233949-56f5af00-7d78-11e9-84c3-2dd14f1e25b2.png)
![image](https://user-images.githubusercontent.com/1254213/58233959-59f09f80-7d78-11e9-97e1-584de0e916f9.png)
![image](https://user-images.githubusercontent.com/1254213/58233961-5bba6300-7d78-11e9-9a2b-6e3423c994c4.png)

Ver2.2.x ClaudiaIDE's background image position and text background color are different from ver2.1.0. But, I got no flickering, maybe; And if I choose large background image, I can show image beyond line number area.

**Comment by buchizo** [comment]
Which do you like better?

I like ver2.2.x style because it's no flickering and expand image to line number area. I don't mind some position offset. It's a trivial issue with big images. However I possibility need to modify image to correct offset in some case.

If you like ver 2.1.0 style, you can use old version from [this vsix in zip](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release2.1.0), and you should set disable automaticaly update in this extensions.

Thanks,

**Comment by AIGRIND-LLC** [comment]
Thanks for the great explanation.
